version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: music_app
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "3100:5432"
  

  backend:
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata: