upstream backend {
    server backend:8001;
}

upstream frontend_server {
    server frontend:8082;
}

# HTTP сервер
server {
    listen 8000;
    server_name au-rooms.ru;

    client_max_body_size 100M;

    # Логи
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # API запросы проксируем на backend
    location /api {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_connect_timeout 60;
        proxy_send_timeout 60;
        proxy_read_timeout 60;
        send_timeout 60;
    }

    # WebSocket соединения
    location /ws {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }

    # Все остальные запросы - на фронтенд
    location / {
        proxy_pass http://frontend_server;
        proxy_http_version 1.1;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_cache_bypass $http_upgrade;
    }
}


# server {
#     listen 443 ssl http2;
#     server_name au-rooms.ru;

#     ssl_certificate /etc/nginx/ssl/live/testops-cloud.ru/fullchain.pem;
#     ssl_certificate_key /etc/nginx/ssl/live/testops-cloud.ru/privkey.pem;

#     client_max_body_size 100M;

#     location /.well-known/acme-challenge/ {
#         root /var/www/certbot;
#     }

#     location /api/ {
#         proxy_pass http://api_backend;
#         proxy_http_version 1.1;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_connect_timeout 300;
#         proxy_send_timeout 300;
#         proxy_read_timeout 300;
#         send_timeout 300;
#     }

#     location / {
#         proxy_pass http://frontend_server;
#         proxy_http_version 1.1;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }
# }
